# Generated by Django 4.0.3 on 2022-03-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_price', models.FloatField(default=0)),
                ('vision_coins', models.FloatField(default=0)),
                ('bonus_coins', models.FloatField(default=0)),
            ],
        ),
    ]
