# Generated by Django 4.0.3 on 2022-04-01 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_plan_offer_end_date_plan_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='offer_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
