# Generated by Django 4.0.3 on 2022-04-01 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_alter_plan_offer_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('order_id', models.SlugField()),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('payment_capture', models.FloatField(default=0)),
                ('order_status', models.CharField(choices=[('Pending', 'pending'), ('Success', 'success')], default=('Pending', 'pending'), max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
