# Generated by Django 4.0.3 on 2022-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plan_benefits',
            field=models.FloatField(default=0),
        ),
    ]
