# Generated by Django 3.2.12 on 2022-03-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagerAPP', '0003_alter_user1_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='is_adult',
            new_name='adult',
        ),
        migrations.RenameField(
            model_name='user1',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='user1',
            old_name='is_superuser',
            new_name='superuser',
        ),
    ]
