# Generated by Django 3.2.12 on 2022-03-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagerAPP', '0004_auto_20220315_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user1',
            name='currency_type',
            field=models.CharField(choices=[('vision coins', 'vision coins'), ('vision candies', 'vision candies')], default=('vision candies', 'vision candies'), max_length=15),
        ),
        migrations.AlterField(
            model_name='user1',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user1',
            name='second_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user1',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
