# Generated by Django 4.0.3 on 2022-05-17 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagerAPP', '0005_alter_user1_currency_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionCurrencyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('currency_type', models.CharField(default='vision candies', max_length=20)),
                ('payment', models.FloatField(default=0)),
                ('payment_add', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
