# Generated by Django 4.0.3 on 2022-05-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagerAPP', '0008_visioncurrencydetails_save_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='contests_won',
            field=models.IntegerField(default=0),
        ),
    ]
