# Generated by Django 4.0.3 on 2022-05-25 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('team1', models.CharField(blank=True, max_length=60, null=True)),
                ('team2', models.CharField(blank=True, max_length=60, null=True)),
                ('is_match_end', models.BooleanField(default=False)),
                ('team1_img', models.TextField(blank=True, null=True)),
                ('team2_img', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('player_name', models.CharField(max_length=50)),
                ('player_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('player_points', models.FloatField(default=7)),
                ('player_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('team_name', models.CharField(max_length=50)),
                ('team_img', models.ImageField(blank=True, null=True, upload_to='team_img')),
                ('team_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_team_points', models.FloatField(default=0)),
                ('captain', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='captain', to='mainAPP.player')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='mainAPP.match')),
                ('players', models.ManyToManyField(to='mainAPP.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vice_captain', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='vice_captain', to='mainAPP.player')),
            ],
        ),
        migrations.CreateModel(
            name='User_Feature_Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=20)),
                ('user_last_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=50)),
                ('feature_title', models.CharField(max_length=100, null=True)),
                ('feature_des', models.TextField(blank=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayersMatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runsScored', models.IntegerField(default=0)),
                ('ballsFaced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('strikeRate', models.FloatField(default=0)),
                ('out', models.BooleanField(default=False)),
                ('overs', models.FloatField(default=0)),
                ('maidens', models.IntegerField(default=0)),
                ('runsGiven', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('wides', models.IntegerField(default=0)),
                ('noBalls', models.IntegerField(default=0)),
                ('economy', models.FloatField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('runouts', models.IntegerField(default=0)),
                ('stumpings', models.IntegerField(default=0)),
                ('points', models.FloatField(default=0)),
                ('additional_points', models.FloatField(default=0)),
                ('match_url', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='mainAPP.match')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPP.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_team',
            field=models.ManyToManyField(to='mainAPP.team'),
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_fee', models.FloatField(default=1)),
                ('fee_type', models.CharField(default='vision candies', max_length=20)),
                ('length', models.IntegerField(default=1)),
                ('price_fee', models.FloatField(default=0)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('contest_type', models.CharField(default='public', max_length=25)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPP.match')),
                ('teams', models.ManyToManyField(to='mainAPP.userteam')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
