# Generated by Django 4.0.3 on 2022-04-30 07:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('url', models.TextField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('player_name', models.CharField(max_length=50)),
                ('player_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('player_points', models.FloatField(default=7)),
                ('player_type', models.CharField(choices=[('WK-Batsman', 'WK-Batsman'), ('Batsman', 'Batsman'), ('Batting Allrounder', 'Batting Allrounder'), ('Bowling Allrounder', 'Bowling Allrounder'), ('Bowler', 'Bowler')], default=('WK-Batsman', 'WK-Batsman'), max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlayersMatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runsScored', models.CharField(max_length=4)),
                ('ballsFaced', models.CharField(max_length=4)),
                ('fours', models.CharField(max_length=4)),
                ('sixes', models.CharField(max_length=4)),
                ('strikeRate', models.CharField(max_length=10)),
                ('out', models.BooleanField()),
                ('overs', models.CharField(max_length=4)),
                ('maidens', models.CharField(max_length=4)),
                ('runsGiven', models.CharField(max_length=4)),
                ('wickets', models.CharField(max_length=4)),
                ('wides', models.CharField(max_length=4)),
                ('noBalls', models.CharField(max_length=4)),
                ('economy', models.CharField(max_length=4)),
                ('catches', models.IntegerField()),
                ('runouts', models.IntegerField()),
                ('stumpings', models.IntegerField()),
                ('points', models.FloatField()),
                ('match_url', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='mainAPP.match')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainAPP.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(to='mainAPP.player'),
        ),
    ]
