# Generated by Django 4.0.3 on 2022-05-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='fee_type',
            field=models.CharField(default='vision candies', max_length=20),
        ),
    ]
