# Generated by Django 4.0.3 on 2022-05-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('team_name', models.CharField(max_length=50)),
                ('team_img', models.ImageField(blank=True, null=True, upload_to='team_img')),
                ('team_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
