# Generated by Django 4.0.3 on 2022-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_pic',
            field=models.ImageField(blank=True, default='https://www.cricbuzz.com/a/img/v1/152x152/i1/c182026/rajat-patidar.jpg', null=True, upload_to=''),
        ),
    ]
