# Generated by Django 4.0.3 on 2022-05-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0002_alter_player_player_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_equal_distribute',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='no_of_winners',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contest',
            name='price_distribution_array',
            field=models.TextField(blank=True, null=True),
        ),
    ]
