# Generated by Django 4.0.3 on 2022-05-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0002_contest_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(default='public', max_length=25),
        ),
    ]
