# Generated by Django 4.0.3 on 2022-05-28 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainAPP', '0003_contest_is_equal_distribute_contest_no_of_winners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='teams',
            field=models.ManyToManyField(blank=True, to='mainAPP.userteam'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
