# Generated by Django 4.0.3 on 2022-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0003_user_feature_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_team',
            field=models.ManyToManyField(to='mainAPP.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(choices=[('BATSMEN', 'BATSMEN'), ('ALL ROUNDER', 'ALL ROUNDER'), ('WICKET KEEPER', 'WICKET KEEPER'), ('BOWLER', 'BOWLER')], default=('BATSMEN', 'BATSMEN'), max_length=30),
        ),
    ]
