# Generated by Django 4.0.3 on 2022-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0003_alter_contest_contest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='player10',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='player11',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='player4',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='player5',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='player6',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='player7',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='player8',
        ),
        migrations.RemoveField(
            model_name='userteam',
            name='player9',
        ),
        migrations.AddField(
            model_name='userteam',
            name='players',
            field=models.ManyToManyField(to='mainAPP.player'),
        ),
    ]
