# Generated by Django 4.0.3 on 2022-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0004_player_player_team_alter_player_player_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(max_length=30),
        ),
    ]
