# Generated by Django 4.0.3 on 2022-05-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0004_remove_userteam_player1_remove_userteam_player10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='total_team_points',
            field=models.FloatField(default=0),
        ),
    ]
