# Generated by Django 4.0.3 on 2022-05-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0005_alter_player_player_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
