# Generated by Django 4.0.3 on 2022-05-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0005_userteam_total_team_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersmatchdata',
            name='catches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playersmatchdata',
            name='out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playersmatchdata',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playersmatchdata',
            name='runouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playersmatchdata',
            name='stumpings',
            field=models.IntegerField(default=0),
        ),
    ]
