# Generated by Django 4.0.3 on 2022-05-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0006_alter_playersmatchdata_catches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersmatchdata',
            name='additional_points',
            field=models.FloatField(default=0),
        ),
    ]
