# Generated by Django 4.0.3 on 2022-05-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0006_match_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
