# Generated by Django 4.0.3 on 2022-05-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0007_remove_match_players_match_team1_match_team2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='url',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
