# Generated by Django 4.0.3 on 2022-05-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0008_alter_match_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_match_end',
            field=models.BooleanField(default=False),
        ),
    ]
