# Generated by Django 4.0.3 on 2022-05-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0009_match_is_match_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
