# Generated by Django 4.0.3 on 2022-05-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPP', '0009_match_is_match_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_feature_suggestion',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
