# Generated by Django 4.0.3 on 2022-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatsupportAPP', '0002_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='group_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
