# Generated by Django 4.0.3 on 2022-04-25 19:35

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('player_points', models.FloatField(default=7)),
                ('player_type', models.CharField(choices=[('wicket_keeper_batsman', 'wicket_keeper_batsman'), ('batsman', 'batsman'), ('all_rounder', 'all_rounder'), ('bowler', 'bowler')], default=('wicket_keeper_batsman', 'wicket_keeper_batsman'), max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='captain', to='records.player')),
                ('player1', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='player1', to='records.player')),
                ('player10', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='player10', to='records.player')),
                ('player11', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='player11', to='records.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='player2', to='records.player')),
                ('player3', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='player3', to='records.player')),
                ('player4', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='player4', to='records.player')),
                ('player5', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='player5', to='records.player')),
                ('player6', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='player6', to='records.player')),
                ('player7', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='player7', to='records.player')),
                ('player8', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='player8', to='records.player')),
                ('player9', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='player9', to='records.player')),
                ('vice_captain', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='vice_captain', to='records.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(to='records.team'),
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_fee', models.FloatField(default=1)),
                ('length', models.IntegerField(default=1)),
                ('price_fee', models.FloatField(default=0)),
                ('teams', models.ManyToManyField(to='records.userteam')),
            ],
        ),
    ]
