# Generated by Django 4.0.3 on 2022-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(choices=[('WK-Batsman', 'WK-Batsman'), ('Batsman', 'Batsman'), ('Batting Allrounder', 'Batting Allrounder'), ('Bowling Allrounder', 'Bowling Allrounder'), ('Bowler', 'Bowler')], default=('WK-Batsman', 'WK-Batsman'), max_length=30),
        ),
    ]
